- name: ubuntu post provision conf
  hosts: ubuntu
  tasks:
  - name: make .ssh dir
    file: 
      path: "/home/{{ ansible_user }}/.ssh"
      state: directory
      mode: 0700

  - name: create auth key file
    file: 
      path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
      state: touch
      mode: 0644
    
  - name: copy over key
    blockinfile:
      dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
      block: "{{ public_key }}"
    
  - name: create sudoers file for 480
    file: 
      path: "/etc/sudoers.d/480"
      state: touch
      mode: 0400
    become: yes

  - name: add sudo entry /etc/sudoers.d/480
    blockinfile:
      dest: "/etc/sudoers.d/480"
      block: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    become: yes

  - name: set hostname
    hostname:
      name: "{{ hostname }}"
    become: yes

  - name: netplan config
    ansible.builtin.template:
      src: ./netplan.yaml
      dest: /etc/netplan/00-installer-config.yaml
      mode: "0644"
      owner: root
      group: root
    become: yes 

  - name: reboot the box
    shell: "sleep 5 && reboot"
    become: yes
    async: 1
    poll: 0