- name: Wazuh Client Install
  hosts: wazuh-client
  tasks:
    - name: Install Agent
      become: yes
      shell: "curl -so wazuh-agent-4.3.11.deb https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.3.11-1_amd64.deb && sudo WAZUH_MANAGER='10.0.5.20' WAZUH_AGENT_GROUP='default' dpkg -i ./wazuh-agent-4.3.11.deb"

    - name: Start service
      become: yes
      shell: "sudo systemctl daemon-reload && sudo systemctl enable wazuh-agent && sudo systemctl start wazuh-agent"